# Generated by Django 5.0.2 on 2024-02-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Blog kategoriya',
                'verbose_name_plural': 'Blog kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Maqola nomi')),
                ('description', models.TextField(verbose_name='Maqola haqida')),
                ('short_description', models.TextField(verbose_name='Maqola qisqacha haqida')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Maqola rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='Maqola kategoriyasi')),
            ],
            options={
                'verbose_name': 'Blog maqola',
                'verbose_name_plural': 'Blog maqolalar',
            },
        ),
    ]
