# Generated by Django 5.0.2 on 2024-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=1, max_length=50, verbose_name='Muallif'),
            preserve_default=False,
        ),
    ]
